name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

permissions:
  contents: write  # 🔐 important for pushing to the output branch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: CodeCommandBD
          outputs: |
            dist/pacman-contribution-graph.svg
          theme: pacman  # 🎮 set pacman theme

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          keep_files: true
